; =============================================================================
; lib/tiles.asm
; -----------------------------------------------------------------------------
; Demo tile and sprite data.
;
; This file contains ROM data. The routines in drawing.asm copy this data to
; VRAM during initialization.
;
; You can replace this file later with:
;   - INCBIN "tiles.bin"
;   - INCBIN "tilemap.bin"
;   - data generated by your own converter
; =============================================================================

; -----------------------------------------------------------------------------
; TilePatterns
; -----------------------------------------------------------------------------
; Four 8x8 patterns. Each byte is one horizontal pixel row.
; Bit 7 is left, bit 0 is right.
; -----------------------------------------------------------------------------
TilePatterns:
        ; TILE_EMPTY: completely empty.
        DB      $00,$00,$00,$00,$00,$00,$00,$00

        ; TILE_WALL: simple border/stone tile.
        DB      $FF,$81,$BD,$A5,$A5,$BD,$81,$FF

        ; TILE_FLOOR: subtle dotted floor.
        DB      $00,$24,$00,$00,$00,$00,$24,$00

        ; TILE_MARKER: small diamond/cross pattern.
        DB      $18,$24,$42,$81,$81,$42,$24,$18
TilePatterns_End:

; -----------------------------------------------------------------------------
; TileColors
; -----------------------------------------------------------------------------
; One color byte per pattern row. Hoge nibble = foreground, low nibble = bg.
; The length must be equal to TILESET_BYTES.
; -----------------------------------------------------------------------------
TileColors:
        ; TILE_EMPTY: black-on-black.
        DB      $11,$11,$11,$11,$11,$11,$11,$11

        ; TILE_WALL: white-on-dark blue.
        DB      $F4,$F4,$F4,$F4,$F4,$F4,$F4,$F4

        ; TILE_FLOOR: green-on-black.
        DB      COLORPAIR_GREEN_BLACK,COLORPAIR_GREEN_BLACK
        DB      COLORPAIR_GREEN_BLACK,COLORPAIR_GREEN_BLACK
        DB      COLORPAIR_GREEN_BLACK,COLORPAIR_GREEN_BLACK
        DB      COLORPAIR_GREEN_BLACK,COLORPAIR_GREEN_BLACK

        ; TILE_MARKER: yellow-on-black.
        DB      COLORPAIR_YELLOW_BLACK,COLORPAIR_YELLOW_BLACK
        DB      COLORPAIR_YELLOW_BLACK,COLORPAIR_YELLOW_BLACK
        DB      COLORPAIR_YELLOW_BLACK,COLORPAIR_YELLOW_BLACK
        DB      COLORPAIR_YELLOW_BLACK,COLORPAIR_YELLOW_BLACK
TileColors_End:

; -----------------------------------------------------------------------------
; DemoTileMap
; -----------------------------------------------------------------------------
; 32 x 24 tilemap for the demo.
; Border = TILE_WALL, inner area = TILE_FLOOR.
; -----------------------------------------------------------------------------
DemoTileMap:
        DS      32,TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DB      TILE_WALL
        DS      30,TILE_FLOOR
        DB      TILE_WALL
        DS      32,TILE_WALL
DemoTileMap_End:

; -----------------------------------------------------------------------------
; SpritePatterns
; -----------------------------------------------------------------------------
; Two 8x8 sprites. Sprite pattern 0 is used by the player.
; -----------------------------------------------------------------------------
SpritePatterns:
        ; Pattern 0: player/ship.
        DB      $18,$3C,$7E,$DB,$FF,$24,$66,$C3

        ; Pattern 1: reserve/enemy marker.
        DB      $18,$3C,$7E,$FF,$DB,$24,$42,$81
SpritePatterns_End:
